=== JOAORSS/Re-Liquid/liquidInterpreter/data/block.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Theme Block Schema",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "limit": {
      "type": "integer"
    },
    "settings": {
      "$ref": "./settings.json"
    }
  },
  "required": [
    "type",
    "name"
  ],
  "additionalProperties": false
}

=== JOAORSS/Re-Liquid/src/components/page-richtext-section/blocks/richtext/richtext.schema.json
{
    "type": "richtext",
    "name": "Rich text",
    "limit": 1,
    "settings": [
    {
        "id": "richtext",
        "type": "richtext",
        "label": "Text",
        "default": "<p>Use this text to share information about your brand with your customers. Describe a product, share announcements, or welcome customers to your store.</p>"
    },
    {
        "type": "url",
        "id": "cta_url",
        "label": "Optional: Call to action link"
    },
    {
        "type": "text",
        "id": "cta_text",
        "label": "Call to action button text"
    }
    ]
}

=== JOAORSS/Re-Liquid/src/components/left-image-tab-section/blocks/crystal-info/crystal-info.schema.json
{
    "type": "richtext",
    "name": "Rich text",
    "limit": 1,
    "settings": [
        {
            "type": "text",
            "id": "title",
            "label": "Heading"
        },
        {
            "type": "richtext",
            "id": "richtext",
            "label": "Intro Text & Subtitle"
        },
        {
            "type": "header",
            "content": "Tab 1 - Read More"
        },
        {
            "type": "text",
            "id": "title-ta",
            "label": "Tab 1 Title"
        },
        {
            "id": "text-ta",
            "type": "richtext",
            "label": "Tab 1 Content"
        },
        {
            "type": "header",
            "content": "Tab 2 - Chakra"
        },
        {
            "type": "text",
            "id": "title-tb",
            "label": "Tab 2 Title"
        },
        {
            "type": "image_picker",
            "id": "image",
            "label": "Tab 2 Image"
        },
        {
            "type": "header",
            "content": "Tab 3 - Details"
        },
        {
            "type": "text",
            "id": "title-tc",
            "label": "Tab 3 Title"
        },
        {
            "type": "richtext",
            "id": "text-tc",
            "label": "Tab 3 Content"
        }
    ]
}

=== JOAORSS/Re-Liquid/src/components/image-tab-section/blocks/richtext/richtext.schema.json
{
    "type": "richtext",
    "name": "Rich text",
    "limit": 1,
    "settings": [
        {
            "id": "title",
            "type": "text",
            "label": "Heading"
        },
        {
            "id": "richtext",
            "type": "richtext",
            "label": "Text",
            "default": "<p>Use this text to share information about your brand with your customers.</p>"
        },
        {
            "type": "header",
            "content": "Title 1"
        },
        {
            "id": "title-ta",
            "type": "text",
            "label": "Heading"
        },
        {
            "type": "header",
            "content": "Info 1"
        },
        {
            "id": "text-ta",
            "type": "richtext",
            "label": "Info"
        },
        {
            "type": "header",
            "content": "Title 2"
        },
        {
            "id": "title-tb",
            "type": "text",
            "label": "Heading"
        },
        {
            "type": "header",
            "content": "Image"
        },
        {
            "type": "image_picker",
            "id": "image",
            "label": "Image"
        },
        {
            "type": "header",
            "content": "Title 3"
        },
        {
            "id": "title-tc",
            "type": "text",
            "label": "Heading"
        },
        {
            "type": "header",
            "content": "Info 3"
        },
        {
            "id": "text-tc",
            "type": "richtext",
            "label": "Info"
        }
    ]
}
